branch-defaults:
  master:
    environment: yuhack-dev
    group_suffix: null
global:
  application_name: yuhack
  branch: null
  default_ec2_keyname: zee-aws
  default_platform: Python 3.4
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
